# Generated by Django 2.0.8 on 2018-11-03 17:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gp_projects', '0007_auto_20181031_0111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenote',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterUniqueTogether(
            name='imagenote',
            unique_together={('timestamp', 'owner')},
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('timestamp', 'owner')},
        ),
    ]
