# Generated by Django 2.0.8 on 2018-11-03 18:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gp_projects', '0008_auto_20181103_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackfeature',
            options={'ordering': ['-timestamp_start']},
        ),
        migrations.AlterUniqueTogether(
            name='trackfeature',
            unique_together={('timestamp_start', 'owner')},
        ),
    ]
