# Generated by Django 2.0.8 on 2018-11-14 18:56

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gp_projects', '0009_auto_20181103_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='TileLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('url_template', models.CharField(help_text='URL template using OSM tile format', max_length=200)),
                ('minZoom', models.IntegerField(default=0)),
                ('maxZoom', models.IntegerField(default=18)),
                ('attribution', models.CharField(max_length=300)),
                ('rank', models.SmallIntegerField(blank=True, help_text='Order of the tilelayers in the edit box', null=True)),
                ('tms', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('center', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='center')),
                ('zoom', models.IntegerField(default=7, verbose_name='zoom')),
                ('modifieddate', models.DateTimeField(auto_now_add=True)),
                ('edit_status', models.SmallIntegerField(choices=[(1, 'Everyone can edit'), (2, 'Only editors can edit'), (3, 'Only owner can edit')], default=3, verbose_name='edit status')),
                ('share_status', models.SmallIntegerField(choices=[(1, 'everyone (public)'), (2, 'anyone with link'), (3, 'editors only')], default=1, verbose_name='share status')),
                ('images', models.ManyToManyField(to='gp_projects.ImageNote')),
                ('notes', models.ManyToManyField(to='gp_projects.Note')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tilelayer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gp_projects.TileLayer')),
                ('tracks', models.ManyToManyField(to='gp_projects.TrackFeature')),
            ],
        ),
    ]
