# Generated by Django 2.0.8 on 2018-11-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp_projects', '0010_tilelayer_usermap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermap',
            name='images',
            field=models.ManyToManyField(blank=True, to='gp_projects.ImageNote'),
        ),
        migrations.AlterField(
            model_name='usermap',
            name='notes',
            field=models.ManyToManyField(blank=True, to='gp_projects.Note'),
        ),
        migrations.RemoveField(
            model_name='usermap',
            name='tilelayer',
        ),
        migrations.AddField(
            model_name='usermap',
            name='tilelayer',
            field=models.ManyToManyField(to='gp_projects.TileLayer'),
        ),
        migrations.AlterField(
            model_name='usermap',
            name='tracks',
            field=models.ManyToManyField(blank=True, to='gp_projects.TrackFeature'),
        ),
    ]
