# Generated by Django 2.0.8 on 2018-11-20 21:12

from django.db import migrations, models
import gp_projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('gp_projects', '0011_auto_20181119_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenote',
            name='webimg',
            field=models.ImageField(default=None, upload_to=gp_projects.models.userdata_directory_path),
            preserve_default=False,
        ),
    ]
